global:
  scrape_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

# read about the rules (not necessary for now?)
# rule_files:
#   - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: api
    static_configs:
      # we are going over a bridge to the host network
      # Prometheus checks out the "/metrics" route
      - targets: [ '172.17.0.1:3001' ]
        labels:
          app: 'api'
